config/routes.rb
Rails.application.routes.draw do
 devise_for :users, controllers: {session: 'users/sessions'}
    devise_for :admins, controllers: {session: 'admins/sessions'}
    
    
  resources :vehiculos
  resources :armas
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
    
    root'armas#index'
end

app/models/vehiculo.rb
class Vehiculo < ApplicationRecord
end

app/controllers/vehiculos_controller.rb
class VehiculosController < ApplicationController
    load_and_authorize_resource param_method: :my_sanitizer
    load_and_authorize_resource :through => :current_user
    
  before_action :set_vehiculo, only: [:show, :edit, :update, :destroy]

  # GET /vehiculos
  # GET /vehiculos.json
  def index
      @vehiculos = Vehiculo.all.page(params[:page]).per(5)
  end

  # GET /vehiculos/1
  # GET /vehiculos/1.json
  def show
  end

  # GET /vehiculos/new
  def new
    @vehiculo = Vehiculo.new
  end

  # GET /vehiculos/1/edit
  def edit
  end

  # POST /vehiculos
  # POST /vehiculos.json
  def create
    @vehiculo = Vehiculo.new(vehiculo_params)

    respond_to do |format|
      if @vehiculo.save
        format.html { redirect_to @vehiculo, notice: 'Vehiculo was successfully created.' }
        format.json { render :show, status: :created, location: @vehiculo }
      else
        format.html { render :new }
        format.json { render json: @vehiculo.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /vehiculos/1
  # PATCH/PUT /vehiculos/1.json
  def update
    respond_to do |format|
      if @vehiculo.update(vehiculo_params)
        format.html { redirect_to @vehiculo, notice: 'Vehiculo was successfully updated.' }
        format.json { render :show, status: :ok, location: @vehiculo }
      else
        format.html { render :edit }
        format.json { render json: @vehiculo.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /vehiculos/1
  # DELETE /vehiculos/1.json
  def destroy
    @vehiculo.destroy
    respond_to do |format|
      format.html { redirect_to vehiculos_url, notice: 'Vehiculo was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_vehiculo
      @vehiculo = Vehiculo.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def vehiculo_params
      params.require(:vehiculo).permit(:tipo, :llantas)
    end
    
    private
      def my_sanitizer
          params.require(:vehiculo).permit(:tipo, :llantas)
  end

    
end

app/helpers/vehiculos_helper.rb
module VehiculosHelper
end

app/views/vehiculos/_form.html.erb
<%= form_for(vehiculo) do |f| %>
  <% if vehiculo.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(vehiculo.errors.count, "error") %> prohibited this vehiculo from being saved:</h2>

      <ul>
      <% vehiculo.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>
<ul class="inline-list">
<div class="row" data-equalizer data-equalizer-mq="large-up">
  <div class="medium-6 columns panel" data-equalizer-watch>
  <div class="field">
    <%= f.label :tipo %>
    <%= f.text_field :tipo %>
  </div>
      </div>
</div>
</ul>

<ul class="inline-list">
<div class="row" data-equalizer data-equalizer-mq="large-up">
  <div class="medium-6 columns panel" data-equalizer-watch>
  <div class="field">
    <%= f.label :llantas %>
    <%= f.text_field :llantas %>
  </div>
 </div>
</div>
</ul>
      
  <section class="row">
<div class="small-4 colums">
  <div class="actions">
    <%= f.submit 'Aceptar',:class => 'button small' %>
  </div>
    </div>

</section>
<% end %>

app/views/vehiculos/edit.html.erb
<h1>Editing Vehiculo</h1>

<%= render 'form', vehiculo: @vehiculo %>

<%= link_to 'Show', @vehiculo %> |
<%= link_to 'Back', vehiculos_path %>

app/views/vehiculos/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Vehiculos</h1>

<table>
  <thead>
    <tr>
      <th>Tipo</th>
      <th>Llantas</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
      <%= paginate @vehiculos %>
      
    <% @vehiculos.each do |vehiculo| %>
      <tr>
        <td><%= vehiculo.tipo %></td>
        <td><%= vehiculo.llantas %></td>
        <td><%= link_to 'Show', vehiculo %></td>
        <td>
            <%if can? :update,@arma %>
            <%= link_to 'Edit', edit_vehiculo_path(vehiculo) %>
            <%end%>
          </td>
        <td>
            <%if can? :destroy,@arma %>
            <%= link_to 'Destroy', vehiculo, method: :delete, data: { confirm: 'Are you sure?' } %>
            <%end%>
          </td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Vehiculo', new_vehiculo_path,  { :class => "button"} %>

app/views/vehiculos/new.html.erb
<h1>New Vehiculo</h1>

<%= render 'form', vehiculo: @vehiculo %>

<%= link_to 'Back', vehiculos_path %>

app/views/vehiculos/show.html.erb
<p>
  <strong>Tipo:</strong>
  <%= @vehiculo.tipo %>
</p>

<p>
  <strong>Llantas:</strong>
  <%= @vehiculo.llantas %>
</p>

<%= link_to 'Edit', edit_vehiculo_path(@vehiculo) %> |
<%= link_to 'Back', vehiculos_path %>