config/routes.rb
Rails.application.routes.draw do
 devise_for :users, controllers: {session: 'users/sessions'}
    devise_for :admins, controllers: {session: 'admins/sessions'}
    
    
  resources :vehiculos
  resources :armas
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
    
    root'armas#index'
end

app/models/arma.rb
class Arma < ApplicationRecord
end

app/controllers/armas_controller.rb
class ArmasController < ApplicationController
    load_and_authorize_resource param_method: :my_sanitizer
    load_and_authorize_resource :through => :current_user
    
  before_action :set_arma, only: [:show, :edit, :update, :destroy]

  # GET /armas
  # GET /armas.json
  def index
      @armas = Arma.all.page(params[:page]).per(5)
  end

  # GET /armas/1
  # GET /armas/1.json
  def show
  end

  # GET /armas/new
  def new
    @arma = Arma.new
  end

  # GET /armas/1/edit
  def edit
  end

  # POST /armas
  # POST /armas.json
  def create
    @arma = Arma.new(arma_params)

    respond_to do |format|
      if @arma.save
        format.html { redirect_to @arma, notice: 'Arma was successfully created.' }
        format.json { render :show, status: :created, location: @arma }
      else
        format.html { render :new }
        format.json { render json: @arma.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /armas/1
  # PATCH/PUT /armas/1.json
  def update
    respond_to do |format|
      if @arma.update(arma_params)
        format.html { redirect_to @arma, notice: 'Arma was successfully updated.' }
        format.json { render :show, status: :ok, location: @arma }
      else
        format.html { render :edit }
        format.json { render json: @arma.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /armas/1
  # DELETE /armas/1.json
  def destroy
    @arma.destroy
    respond_to do |format|
      format.html { redirect_to armas_url, notice: 'Arma was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_arma
      @arma = Arma.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def arma_params
      params.require(:arma).permit(:tipo, :calibte)
    end
    
     private
      def my_sanitizer
          params.require(:arma).permit(:tipo, :calibte)
  end
    
end

app/helpers/armas_helper.rb
module ArmasHelper
end

app/views/armas/_form.html.erb
<%= form_for(arma) do |f| %>
  <% if arma.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(arma.errors.count, "error") %> prohibited this arma from being saved:</h2>

      <ul>
      <% arma.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

<ul class="inline-list">
<div class="row" data-equalizer data-equalizer-mq="large-up">
  <div class="medium-6 columns panel" data-equalizer-watch>
  <div class="field">
    <%= f.label :tipo %>
    <%= f.text_field :tipo %>
  </div>
 </div>
</div>
</ul>
      
    <ul class="inline-list">
<div class="row" data-equalizer data-equalizer-mq="large-up">
  <div class="medium-6 columns panel" data-equalizer-watch>  
  <div class="field">
    <%= f.label :calibte %>
    <%= f.text_field :calibte %>
  </div>
     </div>
</div>
</ul>


<section class="row">
<div class="small-4 colums">
  <div class="actions">
    <%= f.submit 'Aceptar',:class => 'button small' %>
  </div>
    </div>

</section>
<% end %>

app/views/armas/_navigation.html.erb
<div class="top-bar">
  <div class="top-bar-left">
    <ul class="menu" data-dropdown-menu>
      <li class="menu-text"></li>
      <li>
        
      </li>
        <li><%= link_to "armas", controller: "/armas", action: "index" %></li>
        <li> <%= link_to "vehiculos", controller: "/vehiculos", action: "index" %></li>
          
          
          </li>
    </ul>
  </div>



  <div class="top-bar-right">
    <ul class="menu">
        <% if user_signed_in? %>
        <li> <strong><%= current_user.email %></strong> </li>
        <li><%= link_to 'Edit profile', edit_user_registration_path, :class => 'navbar-link' %></li>
       <li> <%= link_to "Logout", destroy_user_session_path, method: :delete, :class => 'navbar-link' %> </li>
       
        <% elsif admin_signed_in? %>
        <li> <strong><%= current_admin.email %></strong> </li>
        <li><%= link_to 'Edit profile', edit_admin_registration_path, :class => 'navbar-link' %></li>
        <li> <%= link_to "Logout", destroy_admin_session_path, method: :delete, :class => 'navbar-link' %> </li>
          <% else %> 
        <li> <%= link_to "Sign up", new_user_registration_path, :class => 'navbar-link' %> </li>
        <li> <%= link_to "Login", new_user_session_path, :class => 'navbar-link' %> </li>
        <li> <%= link_to "Login admin", new_admin_session_path, :class => 'navbar-link' %> </li>
        <% end %>
        
    </ul>
  </div>
</div>




app/views/armas/edit.html.erb
<h1>Editing Arma</h1>

<%= render 'form', arma: @arma %>

<%= link_to 'Show', @arma %> |
<%= link_to 'Back', armas_path %>

app/views/armas/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Armas</h1>

<table>
  <thead>
    <tr>
      <th>Tipo</th>
      <th>Calibte</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
      
      <%= paginate @armas %>
    <% @armas.each do |arma| %>
      <tr>
        <td><%= arma.tipo %></td>
        <td><%= arma.calibte %></td>
        <td><%= link_to 'Show', arma %></td>
          
          
        <td>
            <%if can? :update,@arma %>
            <%= link_to 'Edit', edit_arma_path(arma) %>
            <%end%>
          
          
          </td>
          
          
        <td>
            <%if can? :destroy,@arma %>
            <%= link_to 'Destroy', arma, method: :delete, data: { confirm: 'Are you sure?' } %>
            <%end%>
          </td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Arma', new_arma_path, { :class => "button"} %>

app/views/armas/new.html.erb
<h1>New Arma</h1>

<%= render 'form', arma: @arma %>

<%= link_to 'Back', armas_path%>

app/views/armas/show.html.erb
<p>
  <strong>Tipo:</strong>
  <%= @arma.tipo %>
</p>

<p>
  <strong>Calibte:</strong>
  <%= @arma.calibte %>
</p>

<%= link_to 'Edit', edit_arma_path(@arma) %> |
<%= link_to 'Back', armas_path %>